### ISSUE TITLE
verbose mode for modulel testing

### ISSUE THREAD

**Issue by daviddelikat** [haarg/wgdev#10]
add an option to run tests without Test::Harness/summary so that the user can see all the output. -- makes debugging a single module much easier.

**Comment by haarg** [comment]
Any parameters to the test command that aren't handled by WGDev itself are passed on to the call to prove.  So you can use the -v/--verbose option to get all the output, and -m/--merge if you want to make sure STDOUT & STDERR are properly synchronized.
