### ISSUE TITLE
clearing cache in webgui 8 is borked

### ISSUE THREAD

**Issue by ghost** [haarg/wgdev#13]
$ wgd reset -d
Backing up current database... Done.
Clearing cache... Use of uninitialized value in string eq at /var/folders/Jk/JkyhlQhAEnetkMOHwP55EU+++TI/-Tmp-//WGDev-a28323f9-jtsmith/perl/lib/WGDev/Command/Reset.pm line 208.
Use of uninitialized value in string eq at /var/folders/Jk/JkyhlQhAEnetkMOHwP55EU+++TI/-Tmp-//WGDev-a28323f9-jtsmith/perl/lib/WGDev/Command/Reset.pm line 208.
Done.
Recreating uploads... Done
Clearing old database information... Done.
Importing clean database dump... Done
Running upgrade script... Done
Setting WebGUI settings... Done
Clearing example assets... Done

**Comment by haarg** [comment]
Fixed in c5026e2.
