### ISSUE TITLE
database constraints kill reset

### ISSUE THREAD

**Issue by ghost** [haarg/wgdev#14]
now that the database has constraints you can't just delete the old tables anymore

Clearing old database information... DBD::mysql::db do failed: Cannot delete or update a parent row: a foreign key constraint fails at /var/folders/Jk/JkyhlQhAEnetkMOHwP55EU+++TI/-Tmp-//WGDev-a28323f9-jtsmith/perl/lib/WGDev/Database.pm line 99.

**Comment by haarg** [comment]
Fixed in c274570.
