### ISSUE TITLE
Reset -d fails - looking for missing sql file

### ISSUE THREAD

**Issue by knowmad** [haarg/wgdev#20]
When running `wgd reset -d`, the script fails with following error:

Importing clean database dump... ERROR at line 1: Failed to open file '/data/WebGUI/docs/previousVersion.sql', error: 2

The file is not in the distribution of WebGUI v7.10.13. I made a copy of `create.sql` which seems to be a workaround.

**Comment by haarg** [comment]
The -d option was assuming you were working out of a git checkout instead of possibly a downloaded release.  Fixed.
