### ISSUE TITLE
Pod::Elemental::Transformer::List required for build, but not included in authordeps

### ISSUE THREAD

**Issue by preaction** [haarg/wgdev#21]
After running "dzil authordeps | cpanm", "dzil install" fails because it can't find Pod::Elemental::Transformer::List. Installing the module fixes this problem.

Not sure what dzil include requires this module, otherwise I'd add it to the prereqs list.

**Comment by haarg** [comment]
I've known about this issue, but haven't seen a good way to fix it.

The best option is probably to include information about building from the repository in the README file.

**Comment by haarg** [comment]
Improvements to Dist::Zilla have allowed me to fix this.  I've also included information about building in the README.
